<?php

/**
 * Generated by ZF2ModuleCreator
 */

return [

    'controllers' => [
        'invokables' => [
            'RequestLogger\Controller\Index' => '\RequestLogger\Controller\RequestLoggerController',
        ],
    ],

    'service_manager' => [
    ],

    'console'      => [
        'router' => [],
    ],
    'view_manager' => [
        'template_path_stack' => [
            __DIR__ . '/../view',
        ],
        'strategies' => [
            'ViewJsonStrategy',
        ],
    ],
    'router'       => [
        'routes' => [
            'view_model' => [
                'type'    => 'segment',
                'options' => [
                    'route'    => '/admin/requestlogger[/:action][/:id]',
                    'constraints' => [
                        'action' => '[a-zA-Z]*',
                        'id' => '[a-zA-Z0-9]+',
                    ],
                    'defaults' => [
                        'controller' => 'RequestLogger\Controller\Index',
                        'action'     => 'index',
                    ],
                ],
            ],
        ],

    ],
    'doctrine' => [
      'driver' => [
          'odm_default' => [
              'drivers' => [
                  'RequestLogger\Document\RequestLog' => 'ODM_Driver',
              ],
          ],
      ],
    ],
];